// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://looklerxuuodggtntfdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxvb2tsZXJ4dXVvZGdndG50ZmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxODgwNDYsImV4cCI6MjA5MDc2NDA0Nn0.g7n90rFqUY76kklXmcTT2a7BweSQzRoezQpmuGlQM_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});